/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#291805',
        'surface-variant': '#d9e3f9',
        'primary-container': '#1b2b3a',
        surface: '#f9f9ff',
        'outline-variant': '#c4c6cc',
        'on-surface': '#121c2c',
        'on-surface-variant': '#43474c',
        primary: '#1b2b3a',
        'primary-mobile': '#051625',
        'on-primary-fixed': '#0c1d2b',
        'secondary-container': '#9bb8fe',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-bright': '#f9f9ff',
        'on-tertiary-fixed-variant': '#5a422b',
        outline: '#74777c',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'secondary-fixed': '#d9e2ff',
        'surface-container-high': '#dee8ff',
        'on-secondary-container': '#284785',
        background: '#f9f9ff',
        'secondary-fixed-dim': '#afc6ff',
        'surface-tint': '#506071',
        'surface-dim': '#d0daf0',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        secondary: '#3f5d9c',
        'inverse-surface': '#273141',
        'inverse-on-surface': '#ebf1ff',
        'tertiary-fixed': '#ffdcbe',
        'on-secondary': '#ffffff',
        tertiary: '#221101',
        'on-background': '#121c2c',
        'tertiary-fixed-dim': '#e2c0a2',
        'on-tertiary-container': '#a98b6f',
        'on-secondary-fixed-variant': '#254583',
        'on-primary-container': '#8292a5',
        'inverse-primary': '#b8c8dc',
        'tertiary-container': '#392510',
        'primary-fixed-dim': '#b8c8dc',
        'surface-container-highest': '#d9e3f9',
        'primary-fixed': '#d3e4f8',
        'on-secondary-fixed': '#001944',
        'surface-container': '#e7eeff',
        'on-primary-fixed-variant': '#384858',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'margin-mobile': '16px',
        unit: '4px',
        gutter: '24px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'label-sm': [
          '12px',
          { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-xl': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-md': [
          '14px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
}
